/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes_kelMWU;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yani
 */
public class Employment extends javax.swing.JFrame {

    /**
     * Creates new form Employment
     */
    public Employment() {
        initComponents();
        load_table();
        Fid_pegawai.setEditable(false);
    }
    
    public void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID Pegawai");
        model.addColumn("Nama");
        model.addColumn("Jabatan");
        model.addColumn("No Telp");
        model.addColumn("Alamat");
        model.addColumn("Username");
        model.addColumn("Password");
        
        try {
            int no=1;
            String sql = "SELECT * FROM employee";
            Statement stm= (Statement) koneksi.getConnection().createStatement();
            ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
            }
            tabel_employee.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void cari(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID Pegawai");
        model.addColumn("Nama");
        model.addColumn("Jabatan");
        model.addColumn("No Telp");
        model.addColumn("Alamat");
        model.addColumn("Username");
        model.addColumn("Password");
        
        try {
            int no=1;
            String sql = "SELECT * FROM employee WHERE id_pegawai LIKE '%"+Fcari.getText()+"%'OR Nama_peg LIKE'%"+Fcari.getText()+"%'";
            Statement stm= (Statement) koneksi.getConnection().createStatement();
            ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
            }
            tabel_employee.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public boolean pengecekan(){
        if("".equals(Fnama_peg.getText()) || "".equals(Fnotelp_peg.getText()) || "".equals(Talamat_peg.getText())|| "".equals(Fusername_peg.getText())|| "".equals(Fpassword_peg.getText())){
            return false;
        }else{
            return true;
        } 
    }
    
    public void kosong(){
        Fid_pegawai.setText("");
        Fnama_peg.setText("");
        Cjabatan_peg.setSelectedItem(this);
        Fnotelp_peg.setText("");
        Talamat_peg.setText("");
        Fusername_peg.setText("") ;
        Fpassword_peg.setText("") ;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Fid_pegawai = new javax.swing.JTextField();
        Fnama_peg = new javax.swing.JTextField();
        Fnotelp_peg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_employee = new javax.swing.JTable();
        Btambah = new javax.swing.JButton();
        Bedit = new javax.swing.JButton();
        Bhapus = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Talamat_peg = new javax.swing.JTextArea();
        Fusername_peg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Fpassword_peg = new javax.swing.JTextField();
        Cjabatan_peg = new javax.swing.JComboBox<>();
        Fcari = new javax.swing.JTextField();
        Bcari = new javax.swing.JButton();
        Bback = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 93, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Pegawai : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 58, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jabatan : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 126, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No Telp : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 169, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 226, -1, -1));
        jPanel1.add(Fid_pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 58, 231, -1));
        jPanel1.add(Fnama_peg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 93, 229, -1));
        jPanel1.add(Fnotelp_peg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 168, 229, -1));

        tabel_employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_employeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_employee);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 58, -1, 326));

        Btambah.setText("Tambah");
        Btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtambahActionPerformed(evt);
            }
        });
        jPanel1.add(Btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 356, -1, -1));

        Bedit.setText("Edit");
        Bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeditActionPerformed(evt);
            }
        });
        jPanel1.add(Bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 399, 75, -1));

        Bhapus.setText("Hapus");
        Bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhapusActionPerformed(evt);
            }
        });
        jPanel1.add(Bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 356, -1, -1));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 399, -1, -1));

        Talamat_peg.setColumns(20);
        Talamat_peg.setRows(5);
        jScrollPane2.setViewportView(Talamat_peg);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 208, 229, 61));
        jPanel1.add(Fusername_peg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 282, 229, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 285, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 319, -1, -1));
        jPanel1.add(Fpassword_peg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 316, 229, -1));

        Cjabatan_peg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Kurir" }));
        jPanel1.add(Cjabatan_peg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 122, -1, 28));
        jPanel1.add(Fcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 27, 191, -1));

        Bcari.setText("Cari");
        Bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcariActionPerformed(evt);
            }
        });
        jPanel1.add(Bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 26, -1, -1));

        Bback.setText("Back");
        Bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbackActionPerformed(evt);
            }
        });
        jPanel1.add(Bback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 13, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes_kelMWU/Employee.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtambahActionPerformed
        // TODO add your handling code here: 
        String nama = Fnama_peg.getText();
        String jabatan = Cjabatan_peg.getSelectedItem().toString();
        String noTelp= Fnotelp_peg.getText();
        String alamat= Talamat_peg.getText();
        String username= Fusername_peg.getText() ;
        String password= Fpassword_peg.getText() ;
        if(pengecekan()){
            try {
                String sql = "INSERT INTO employee VALUES ('"+0+"','"+nama+"','"+jabatan+"','"+noTelp+"','"+alamat+"','"+username+"','"+password+"')";
                Connection conn= koneksi.getConnection();
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
            }catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            load_table();
            kosong();
        }else{
            JOptionPane.showMessageDialog(null, "Semua data harus di isi");
        }
        
        
    }//GEN-LAST:event_BtambahActionPerformed

    private void BeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeditActionPerformed
        // TODO add your handling code here:
        String id_peg = Fid_pegawai.getText();
        String nama = Fnama_peg.getText();
        String jabatan = Cjabatan_peg.getSelectedItem().toString();
        String noTelp= Fnotelp_peg.getText();
        String alamat= Talamat_peg.getText();
        String username= Fusername_peg.getText() ;
        String password= Fpassword_peg.getText() ;
        if(pengecekan() && !"".equals(id_peg)){
           String sql = "UPDATE employee SET id_pegawai='"+id_peg+"',Nama_peg='"+nama+"',Jabatan_peg='"+jabatan+"',NoTelp_peg='"+noTelp+"',Alamat_peg='"+alamat+"',Username_peg='"+username+"',Password_peg='"+password+"' WHERE id_pegawai='"+id_peg+"'";
            try{
                Connection conn = koneksi.getConnection();
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil di-update di database");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            load_table();
            kosong(); 
        }else{
            JOptionPane.showMessageDialog(null, "Semua data harus di isi");
        }
    }//GEN-LAST:event_BeditActionPerformed

    private void BhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhapusActionPerformed
        // TODO add your handling code here:
        if(!"".equals(Fid_pegawai.getText())){
            String sql = "DELETE FROM employee WHERE id_pegawai='"+Fid_pegawai.getText()+"'";
            try{
                Connection conn = koneksi.getConnection();
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus di database");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            load_table();
            kosong();
        }else{
            JOptionPane.showMessageDialog(null, "Pilih data yang mau dihapus!!");
        }
        
    }//GEN-LAST:event_BhapusActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        kosong();
        load_table();
    }//GEN-LAST:event_resetActionPerformed

    private void tabel_employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_employeeMouseClicked
        // TODO add your handling code here:
        int baris = tabel_employee.rowAtPoint(evt.getPoint());
        String id_peg =tabel_employee.getValueAt(baris, 1).toString();
        Fid_pegawai.setText(id_peg);
        String nama = tabel_employee.getValueAt(baris,2).toString();
        Fnama_peg.setText(nama);
        String jabatan = tabel_employee.getValueAt(baris, 3).toString();
        Cjabatan_peg.setSelectedItem(jabatan);
        String noTelp =tabel_employee.getValueAt(baris, 4).toString();
        Fnotelp_peg.setText(noTelp);
        String alamat = tabel_employee.getValueAt(baris, 5).toString();
        Talamat_peg.setText(alamat);
        String username = tabel_employee.getValueAt(baris,6).toString();
        Fusername_peg.setText(username);
        String password = tabel_employee.getValueAt(baris,7).toString();
        Fpassword_peg.setText(password);
    }//GEN-LAST:event_tabel_employeeMouseClicked

    private void BcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcariActionPerformed
        // TODO add your handling code here:
        cari();
        kosong();
    }//GEN-LAST:event_BcariActionPerformed

    private void BbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbackActionPerformed
        // TODO add your handling code here:
        MenuAdmin menuAdmin = new MenuAdmin();
        menuAdmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bback;
    private javax.swing.JButton Bcari;
    private javax.swing.JButton Bedit;
    private javax.swing.JButton Bhapus;
    private javax.swing.JButton Btambah;
    private javax.swing.JComboBox<String> Cjabatan_peg;
    private javax.swing.JTextField Fcari;
    private javax.swing.JTextField Fid_pegawai;
    private javax.swing.JTextField Fnama_peg;
    private javax.swing.JTextField Fnotelp_peg;
    private javax.swing.JTextField Fpassword_peg;
    private javax.swing.JTextField Fusername_peg;
    private javax.swing.JTextArea Talamat_peg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton reset;
    private javax.swing.JTable tabel_employee;
    // End of variables declaration//GEN-END:variables
}
