/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes_kelMWU;

/**
 *
 * @author yani
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Mcustomer = new javax.swing.JButton();
        Morder = new javax.swing.JButton();
        Mshipment = new javax.swing.JButton();
        Mservice = new javax.swing.JButton();
        Memployee = new javax.swing.JButton();
        Blogout = new javax.swing.JToggleButton();
        Luser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Admin");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 13, -1, -1));

        Mcustomer.setText("Menu Customer");
        Mcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                McustomerActionPerformed(evt);
            }
        });
        jPanel2.add(Mcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 305, -1));

        Morder.setText("Menu Orderpacket");
        Morder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MorderActionPerformed(evt);
            }
        });
        jPanel2.add(Morder, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 305, -1));

        Mshipment.setText("Menu Shipment");
        Mshipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MshipmentActionPerformed(evt);
            }
        });
        jPanel2.add(Mshipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 305, -1));

        Mservice.setText("Menu Service");
        Mservice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MserviceActionPerformed(evt);
            }
        });
        jPanel2.add(Mservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 305, -1));

        Memployee.setText("Menu Employee");
        Memployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemployeeActionPerformed(evt);
            }
        });
        jPanel2.add(Memployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 305, -1));

        Blogout.setText("Log out");
        Blogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlogoutActionPerformed(evt);
            }
        });
        jPanel2.add(Blogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Luser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Luser.setForeground(new java.awt.Color(255, 255, 255));
        Luser.setText("ADMIN");
        jPanel2.add(Luser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes_kelMWU/Menu admin.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void McustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_McustomerActionPerformed
        // TODO add your handling code here:
        Customer customer = new Customer();
        customer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_McustomerActionPerformed

    private void MorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MorderActionPerformed
        // TODO add your handling code here:
        Order order = new Order();
        order.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MorderActionPerformed

    private void MshipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MshipmentActionPerformed
        // TODO add your handling code here:
        Shipment shipment = new Shipment();
        shipment.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MshipmentActionPerformed

    private void MserviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MserviceActionPerformed
        // TODO add your handling code here:
        Service service = new Service();
        service.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MserviceActionPerformed

    private void MemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemployeeActionPerformed
        // TODO add your handling code here:
        Employment employment = new Employment();
        employment.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MemployeeActionPerformed

    private void BlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlogoutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Blogout;
    protected javax.swing.JLabel Luser;
    private javax.swing.JButton Mcustomer;
    private javax.swing.JButton Memployee;
    private javax.swing.JButton Morder;
    private javax.swing.JButton Mservice;
    private javax.swing.JButton Mshipment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
