/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes_kelMWU;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author naufa
 */
public class Shipment extends javax.swing.JFrame {

    /**
     * Creates new form Shipment
     */
    public Shipment() {
        initComponents();
        load_table();
        Fresi.setEditable(false);
        Fid_paket.setEditable(false);
        Fbiayapengiriman.setEditable(false);
    }

    public void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("No Resi");
        model.addColumn("ID paket");
        model.addColumn("Nama penerima");
        model.addColumn("NoHP penerima");
        model.addColumn("Alamat penerima");
        model.addColumn("Biaya Pengiriman");
        model.addColumn("Jenis service");
        model.addColumn("Tanggal Pengiriman");
        model.addColumn("Tanggal Sampai");
        model.addColumn("Status");
        try {
            int no=1;
            String sql = "SELECT shipment.* ,order_paket.*, service.* FROM shipment "
                    + "JOIN order_paket ON (shipment.id_paket = order_paket.id_paket)"
                    + "JOIN service ON (order_paket.id_service = service.id_service)";
            Statement stm = (Statement) koneksi.getConnection().createStatement();
            ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString("no_resi"),res.getString("id_paket"),res.getString("nama_penerima"),res.getString("noHp_penerima"),res.getString("alamat_tujuan"),res.getString("biaya_pengiriman"),res.getString("title_service"),res.getString("tanggal_pengiriman"),res.getString("tanggal_sampai"),res.getString("status")});
            }
            table_shipment.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void cari(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("No Resi");
        model.addColumn("ID paket");
        model.addColumn("Nama penerima");
        model.addColumn("NoHP penerima");
        model.addColumn("Alamat penerima");
        model.addColumn("Biaya Pengiriman");
        model.addColumn("Jenis service");
        model.addColumn("Tanggal Pengiriman");
        model.addColumn("Tanggal Sampai");
        model.addColumn("Status");
        
        try {
            int no=1;
            String sql = "SELECT shipment.* ,order_paket.*, service.* FROM shipment "
                    + "JOIN order_paket ON (shipment.id_paket = order_paket.id_paket)"
                    + "JOIN service ON (order_paket.id_service = service.id_service)"
                    + "WHERE no_resi LIKE '%"+Fcari.getText()+"%'";
            Statement stm= (Statement) koneksi.getConnection().createStatement();
            ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString("no_resi"),res.getString("id_paket"),res.getString("nama_penerima"),res.getString("noHp_penerima"),res.getString("alamat_tujuan"),res.getString("biaya_pengiriman"),res.getString("title_service"),res.getString("tanggal_pengiriman"),res.getString("tanggal_sampai"),res.getString("status")});
            }
            table_shipment.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fresi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Fbiayapengiriman = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Ftanggalkirim = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Ftanggalsampai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_shipment = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        Fstatus = new javax.swing.JTextField();
        createShipment = new javax.swing.JButton();
        updateShipment = new javax.swing.JButton();
        deleteShipment = new javax.swing.JButton();
        searchShipment = new javax.swing.JButton();
        Fcari = new javax.swing.JTextField();
        resetShipment = new javax.swing.JButton();
        Bback = new javax.swing.JButton();
        Fid_paket = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel5.setText("Biaya Pengiriman: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Shipment");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. Resi :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        Fresi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FresiActionPerformed(evt);
            }
        });
        jPanel1.add(Fresi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 158, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Biaya Pengiriman: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel1.add(Fbiayapengiriman, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 158, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal Pengiriman :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        jPanel1.add(Ftanggalkirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 158, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal Sampai :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
        jPanel1.add(Ftanggalsampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 158, -1));

        table_shipment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_shipment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_shipmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_shipment);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 560, 393));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        Fstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FstatusActionPerformed(evt);
            }
        });
        jPanel1.add(Fstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 158, -1));

        createShipment.setText("Add Shipment");
        createShipment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createShipmentMouseClicked(evt);
            }
        });
        createShipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createShipmentActionPerformed(evt);
            }
        });
        jPanel1.add(createShipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 320, 130, -1));

        updateShipment.setText("Update Shipment");
        updateShipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateShipmentActionPerformed(evt);
            }
        });
        jPanel1.add(updateShipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        deleteShipment.setText("Delete Shipment");
        deleteShipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteShipmentActionPerformed(evt);
            }
        });
        jPanel1.add(deleteShipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        searchShipment.setText("Cari");
        searchShipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchShipmentActionPerformed(evt);
            }
        });
        jPanel1.add(searchShipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));
        jPanel1.add(Fcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 156, -1));

        resetShipment.setText("Reset");
        resetShipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetShipmentActionPerformed(evt);
            }
        });
        jPanel1.add(resetShipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 131, -1));

        Bback.setText("Back");
        Bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbackActionPerformed(evt);
            }
        });
        jPanel1.add(Bback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        Fid_paket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fid_paketActionPerformed(evt);
            }
        });
        jPanel1.add(Fid_paket, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 158, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID paket :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes_kelMWU/A_shipment.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FstatusActionPerformed

    private void table_shipmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_shipmentMouseClicked
        // TODO add your handling code here:
        int baris = table_shipment.rowAtPoint(evt.getPoint());
        String no_resi =table_shipment.getValueAt(baris, 1).toString();
        Fresi.setText(no_resi);
        String id_paket = table_shipment.getValueAt(baris, 2).toString();
        Fid_paket.setText(id_paket); 
        String biayaPengiriman = table_shipment.getValueAt(baris,6).toString();
        Fbiayapengiriman.setText(biayaPengiriman);
        String tanggalPengiriman = table_shipment.getValueAt(baris, 8).toString();
        Ftanggalkirim.setText(tanggalPengiriman);
        String tanggalSampai = table_shipment.getValueAt(baris, 9).toString();
        Ftanggalsampai.setText(tanggalSampai);
        String status = table_shipment.getValueAt(baris, 10).toString();
        Fstatus.setText(status);
        
    }//GEN-LAST:event_table_shipmentMouseClicked

    private void createShipmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createShipmentMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_createShipmentMouseClicked

    private void createShipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createShipmentActionPerformed
        // TODO add your handling code here:
        String biayaPengiriman = Fbiayapengiriman.getText();
        String tanggalPengiriman = Ftanggalkirim.getText();
        String tanggalSampai = Ftanggalsampai.getText();
        String status = Fstatus.getText();
        String idpaket = Fid_paket.getText();
        
        try {
            String sql = "INSERT INTO shipment VALUES ('"+0+"','"+idpaket+"','"+biayaPengiriman+"','"+tanggalPengiriman+"','"+tanggalSampai+"','"+status+"')";
            Connection conn= koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        load_table();
    }//GEN-LAST:event_createShipmentActionPerformed

    private void updateShipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateShipmentActionPerformed
        // TODO add your handling code here:
        String no_resi = Fresi.getText();
        String idpaket = Fid_paket.getText();
        String biayaPengiriman = Fbiayapengiriman.getText();
        String tanggalPengiriman = Ftanggalkirim.getText();
        String tanggalSampai = Ftanggalsampai.getText();
        String status = Fstatus.getText();
        
        String sql = "UPDATE shipment SET no_resi='"+no_resi+"',id_paket='"+idpaket+"',biaya_pengiriman='"+biayaPengiriman+"',tanggal_pengiriman='"+tanggalPengiriman+"',tanggal_sampai='"+tanggalSampai+"',status='"+status+"' WHERE no_resi='"+no_resi+"'";
        try{
            Connection conn = koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil di-update di database");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        load_table();
    }//GEN-LAST:event_updateShipmentActionPerformed

    private void deleteShipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteShipmentActionPerformed
        // TODO add your handling code here:
        String sql = "DELETE FROM shipment WHERE no_resi='"+Fresi.getText()+"'";
        try{
            Connection conn = koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus di database");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        load_table();
    }//GEN-LAST:event_deleteShipmentActionPerformed

    private void resetShipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetShipmentActionPerformed
        // TODO add your handling code here:
        Fresi.setText("");
        Fid_paket.setText("");
        Fbiayapengiriman.setText("");
        Fstatus.setText("");
        Ftanggalkirim.setText("");
        Ftanggalsampai.setText("");
        load_table();
    }//GEN-LAST:event_resetShipmentActionPerformed

    private void FresiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FresiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FresiActionPerformed

    private void searchShipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchShipmentActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_searchShipmentActionPerformed

    private void BbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbackActionPerformed
        // TODO add your handling code here:
        MenuAdmin MA = new MenuAdmin();
        MA.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BbackActionPerformed

    private void Fid_paketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fid_paketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fid_paketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shipment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bback;
    protected javax.swing.JTextField Fbiayapengiriman;
    private javax.swing.JTextField Fcari;
    protected javax.swing.JTextField Fid_paket;
    private javax.swing.JTextField Fresi;
    protected javax.swing.JTextField Fstatus;
    private javax.swing.JTextField Ftanggalkirim;
    private javax.swing.JTextField Ftanggalsampai;
    private javax.swing.JButton createShipment;
    private javax.swing.JButton deleteShipment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton resetShipment;
    private javax.swing.JButton searchShipment;
    private javax.swing.JTable table_shipment;
    private javax.swing.JButton updateShipment;
    // End of variables declaration//GEN-END:variables
}
